update and clean up README.md
bcgov/design-system pull request #337
Opened 2024-04-22 18:53 UTC by mkernohanbc

This change is a minor refresh of README.md to reflect current status of work on the design system:

- Adds links to new resources publishing alongside 3.0.0 release
- Updates status of DS sub-products
- Updates language around archiving of legacy design system resources
- General content cleanup

2024-04-23 20:00 UTC, ty2k requested changes
Content is all good, but there's two small formatting changes we should make:

2024-04-23 20:00 UTC, ty2k commented on README.md
> -    Licensed under the Apache License, Version 2.0 (the "License");
Without these line breaks, this block overflows:

<img width="1046" alt="Screenshot 2024-04-23 at 12 58 30 PM" src="https://github.com/bcgov/design-system/assets/25143706/a4dcd8b2-49a6-4f7a-9dca-ae1157c32490">

Maybe we just take this summary license section out entirely and replace it with "See LICENSE file"?

2024-04-24 17:17 UTC, mkernohanbc commented on README.md
> -    Licensed under the Apache License, Version 2.0 (the "License");
Weird! I think you're right — now that I think about it more closely, I don't know why this section is here at all. We have LICENSE.md accessible right here: 

<img width="912" alt="Screenshot 2024-04-24 at 10 10 49" src="https://github.com/bcgov/design-system/assets/135075821/7969f72b-882f-4b64-a71f-b09ee7db5b3d">

I've just made another commit (3f6742b) to remove that paragraph from README.md entirely.

2024-05-01 21:50 UTC, mkernohanbc commented on README.md
> +> [!NOTE] > **April 2024**: The B.C. Design System is currently in active development. If you have questions, [contact the design system team](#contact) or [open an issue](https://github.com/bcgov/de
This is fixed (I think?) in [04d6a4d](https://github.com/bcgov/design-system/pull/337/commits/04d6a4d9a8750215a8676094587e4eb1309937b1)

2024-05-01 22:38 UTC, ty2k approved these changes
Looks great!

2024-05-01 22:48 UTC, merged